language: java

jdk:
  - oraclejdk8

branches:
  except:
    - gh-pages

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade -y oracle-java8-installer
  - java -version
  - mvn --version
